import "server-only";

import { z } from "zod";
import type { ActiveAiMode } from "@/lib/ai-mode";
import {
  isLlmNodeKind,
  isMediaPlaceholderKind,
  NODE_SYSTEM_INSTRUCTIONS,
} from "@/lib/agent/node-instructions";
import { isFallbackEligible } from "@/lib/agent/planner";
import {
  executeDemoNode,
  type UpstreamOutputs as DemoUpstreamMap,
} from "@/lib/demo";
import {
  chatStructured,
  OllamaClientError,
  type OllamaConfig,
} from "@/lib/ollama";
import {
  CreativeBrief,
  NodeExecutionResult,
  NodeExecutionResultSchema,
  NodeRunStatus,
  WorkflowNode,
  WorkflowNodeKindSchema,
} from "@/lib/workflow";

export type UpstreamOutputItem = {
  nodeId: string;
  nodeLabel: string;
  result: NodeExecutionResult;
};

export type RunNodeSuccess = {
  result: NodeExecutionResult;
  status: NodeRunStatus;
  activeMode: ActiveAiMode;
  model: string | null;
  durationMs: number;
};

const FORBIDDEN_SETTING_KEYS = new Set([
  "provider_url",
  "ollama_url",
  "base_url",
  "endpoint",
  "api_url",
  "webhook_url",
]);

export class NodeExecutionError extends Error {
  readonly code: string;
  readonly retryable: boolean;

  constructor(code: string, message: string, retryable = false) {
    super(message);
    this.name = "NodeExecutionError";
    this.code = code;
    this.retryable = retryable;
  }
}

/** Strip client-supplied provider URLs / endpoints from settings. */
export function sanitizeNodeForExecution(node: WorkflowNode): WorkflowNode {
  return {
    ...node,
    config: {
      ...node.config,
      settings: node.config.settings.filter(
        (s) =>
          !FORBIDDEN_SETTING_KEYS.has(s.key.toLowerCase()) &&
          !/^https?:\/\//i.test(s.value),
      ),
    },
  };
}

export function assertExecutableNode(node: WorkflowNode): void {
  const kind = WorkflowNodeKindSchema.safeParse(node.kind);
  if (!kind.success) {
    throw new NodeExecutionError("unknown_node_kind", "Unknown node kind.", false);
  }
  if (!node.config.enabled) {
    throw new NodeExecutionError(
      "node_disabled",
      "Cannot execute a disabled node.",
      false,
    );
  }
}

function toDemoUpstream(items: UpstreamOutputItem[]): DemoUpstreamMap {
  const map: DemoUpstreamMap = {};
  for (const item of items) {
    map[item.nodeId] = item.result;
  }
  return map;
}

function mediaPlaceholderResult(
  node: WorkflowNode,
  brief: CreativeBrief,
): { result: NodeExecutionResult; status: NodeRunStatus } {
  const label = node.label || node.kind;
  return {
    status: "needs_provider",
    result: {
      summary: `${label} requires a generation provider for ${brief.product}.`,
      artifacts: [
        {
          id: `${node.kind}_placeholder`,
          name: `${label} (simulated)`,
          type: "text/plain",
          content: `Simulated ${node.kind} placeholder for “${brief.product}” (${brief.tone}, ${brief.aspectRatio}). No generation provider is connected.`,
          simulated: true,
        },
      ],
      decisions: [`Keep ${node.kind} marked as provider-dependent`],
      warnings: [
        "A generation provider is not connected. This artifact is simulated and was not generated by a real media API.",
        "Workflow logic completed; connect a generation provider to render this asset.",
      ],
    },
  };
}

function briefInputResult(brief: CreativeBrief): NodeExecutionResult {
  return {
    summary: `Brief loaded for ${brief.product}.`,
    artifacts: [
      {
        id: "brief_snapshot",
        name: "Creative brief",
        type: "application/json",
        content: JSON.stringify(brief, null, 2),
        simulated: false,
      },
    ],
    decisions: ["Use validated brief as source of truth"],
    warnings: [],
  };
}

async function executeWithOllama(
  node: WorkflowNode,
  brief: CreativeBrief,
  upstream: UpstreamOutputItem[],
  config: OllamaConfig,
  fetchImpl?: typeof fetch,
): Promise<{ result: NodeExecutionResult; model: string; durationMs: number }> {
  if (!isLlmNodeKind(node.kind)) {
    throw new NodeExecutionError(
      "not_llm_node",
      `Node kind ${node.kind} is not LLM-backed.`,
      false,
    );
  }

  const jsonSchema = z.toJSONSchema(NodeExecutionResultSchema) as Record<
    string,
    unknown
  >;
  const system = NODE_SYSTEM_INSTRUCTIONS[node.kind];
  const started = Date.now();

  const response = await chatStructured({
    messages: [
      { role: "system", content: system },
      {
        role: "user",
        content: [
          `Node: ${node.id} (${node.kind}) — ${node.label}`,
          `Instruction: ${node.config.instruction}`,
          `Brief: ${JSON.stringify(brief)}`,
          `Upstream outputs: ${JSON.stringify(upstream)}`,
          "Return only NodeExecutionResult JSON matching the schema.",
          JSON.stringify(jsonSchema),
        ].join("\n"),
      },
    ],
    schema: NodeExecutionResultSchema,
    schemaName: "NodeExecutionResult",
    config,
    fetchImpl,
    jsonSchema,
  });

  return {
    result: response.data,
    model: response.model,
    durationMs: Math.max(response.durationMs, Date.now() - started),
  };
}

export type ExecuteNodeParams = {
  node: WorkflowNode;
  brief: CreativeBrief;
  upstreamOutputs: UpstreamOutputItem[];
  activeMode: ActiveAiMode;
  config?: OllamaConfig;
  fetchImpl?: typeof fetch;
  forceDemo?: boolean;
};

/**
 * Execute a single node. Never runs node-supplied code or client provider URLs.
 */
export async function executeWorkflowNode(
  params: ExecuteNodeParams,
): Promise<RunNodeSuccess> {
  const started = Date.now();
  const node = sanitizeNodeForExecution(params.node);
  assertExecutableNode(node);

  if (node.kind === "brief_input") {
    return {
      result: briefInputResult(params.brief),
      status: "completed",
      activeMode: params.activeMode,
      model: null,
      durationMs: Date.now() - started,
    };
  }

  if (isMediaPlaceholderKind(node.kind)) {
    const placeholder = mediaPlaceholderResult(node, params.brief);
    return {
      ...placeholder,
      activeMode: params.activeMode,
      model: null,
      durationMs: Date.now() - started,
    };
  }

  const useDemo = params.forceDemo || params.activeMode === "demo";

  if (useDemo || !isLlmNodeKind(node.kind)) {
    const result = await executeDemoNode({
      node,
      brief: params.brief,
      upstreamOutputs: toDemoUpstream(params.upstreamOutputs),
      skipDelay: process.env.NODE_ENV === "test",
    });
    return {
      result,
      status: "completed",
      activeMode: useDemo ? "demo" : params.activeMode,
      model: null,
      durationMs: Date.now() - started,
    };
  }

  if (!params.config) {
    throw new OllamaClientError(
      "ollama_config_invalid",
      "Ollama config required for LLM node execution.",
      { retryable: false },
    );
  }

  const { result, model, durationMs } = await executeWithOllama(
    node,
    params.brief,
    params.upstreamOutputs,
    params.config,
    params.fetchImpl,
  );
  return {
    result,
    status: "completed",
    activeMode: "ollama",
    model,
    durationMs,
  };
}

export { isFallbackEligible };
